### PR TITLE
Song profile

### PR DESCRIPTION
**Pull request by Heinrich-XIAO**
#462

### CODE REVIEW

**Comment by Heinrich-XIAO** [comment]
This is pretty much done. Tell me if I should change anything.

**Comment by gokadzev** [comment]
Individual volume control for each song? doesn't make any sense and haven't seen anywhere such thing. sorry, I'm still pessimistic towards to this feature.

**Comment by Heinrich-XIAO** [comment]
I know it's not anywhere else (to my knowledge) but it is useful to some people (at least me).

**Comment by Heinrich-XIAO** [comment]
It let's you have a playlist go without having to change volume each time, this is especially useful if you listen to music sleeping as you are more sensitive to small changes in volume.

**Comment by gokadzev** [comment]
> It let's you have a playlist go without having to change volume each time, this is especially useful if you listen to music sleeping as you are more sensitive to small changes in volume.

Well, this PR is broken, and a separate page for it wouldn't be a good idea for the volume feature. This means we need to integrate it into the Now Playing page, which is quite complex as that page has been unresponsive on different screens for a long time. Even now, I'm not sure it looks perfect on every screen size.

**Comment by Heinrich-XIAO** [comment]
Well, I'm going to add more options to that page.

**Pull request closed without merging**
