### PR TITLE
Update app_pt.arb

### PR DESCRIPTION
**Pull request by GeovaneSec**

### CODE REVIEW

**Comment by gokadzev** [comment]
@GeovaneSec Hi, Thanks for this PR. I had to add one more localization that I'm going to push in several minutes, will you change it too or I can merge this commit already?

**Comment by GeovaneSec** [comment]
Yes, I can update the upcoming commits with that localization as well.

**Comment by gokadzev** [comment]
> Yes, I can update the upcoming commits with that localization as well.

Perfect, no need to close tho, just make changes in the same branch and it'll appear here too

**Comment by GeovaneSec** [comment]
I have made a new pull, with only one commit.

**Pull request closed without merging**
