### PR TITLE
fix(playlist): check if song is already in playlist

### LINKED ISSUE #459: [Bug] Adding a song multiple times into a playlist
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [ ] I will fill out all the sections in this issue report.

### Current Behavior

It is possible to add a song multiple times into the same playlist.

### Expected Behavior

Adding a song multiple times into a playlist should not be possible.

### Steps To Reproduce

1. Make a playlist.
2. Add a song into the playlist.
3. Add the song into the playlist again.

### Musify Version

7e8aa0839a9f5a4b3c024b51ca4e9b7b9004e6d3 or v8.7.5

### Device And Operating System

Huawei IDK the device name and its not realivent

### Android Version You Use

IDK

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Heinrich-XIAO**
Fixes #459

### CODE REVIEW

**Comment by gokadzev** [comment]
I just noticed that in this function, I used String responses as returns, but they're not actually used anywhere, nor are they translated.

**Comment by Heinrich-XIAO** [comment]
Should I remove them?

**Comment by Heinrich-XIAO** [comment]
Also, it never has a way of saying the adding failed. It always says song added.

**Comment by gokadzev** [comment]
> Should I remove them?

No actually, I guess I need to add localizations for them and make a toast notification for this and then I'll be able to merge this PR

**Pull request merged**
